### ISSUE TITLE
Does not process line-height for `16px/1.2 Georgia,serif`

### ISSUE THREAD

**Issue by atn832** [tmpvar/cssfontparser#3]
Hi Elijah,

`parse` fails line-height from the following string: `16px/1.2 Georgia,serif`. I debugged and saw that it actually finds the value, but then sets it to null at https://github.com/tmpvar/cssfontparser/blob/master/index.js#L132

How can this be fixed?

**Comment by tmpvar** [comment]
ok, so the fix is directly at odds with an existing test - pull here: #5

what do you think?

**Comment by atn832** [comment]
Yes, that's great, thank you!
